// Auto-generated by export-abi.ts
// Do not edit manually

export const HONEST_CARD_ADDRESS = "0x97fbe4323C39E95127c0F5fd4Fc79C4450890334" as const;

export const HONEST_CARD_ABI = [
  {
    "inputs": [],
    "name": "AlreadyRequested",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CannotExchangeWithSelf",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CardAlreadyExists",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CardNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ExchangeNotCompleted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZamaProtocolUnsupported",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "surname",
        "type": "string"
      }
    ],
    "name": "CardCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "CardUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "ExchangeCancelled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "partyA",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "partyB",
        "type": "address"
      }
    ],
    "name": "ExchangeCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "ExchangeRequested",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "cancelRequest",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "confidentialProtocolId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "surname",
        "type": "string"
      },
      {
        "internalType": "externalEuint8",
        "name": "gender",
        "type": "bytes32"
      },
      {
        "internalType": "externalEuint64",
        "name": "phone",
        "type": "bytes32"
      },
      {
        "internalType": "externalEuint64",
        "name": "fullName",
        "type": "bytes32"
      },
      {
        "internalType": "externalEuint128",
        "name": "socialId",
        "type": "bytes32"
      },
      {
        "internalType": "externalEuint256",
        "name": "location",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "inputProof",
        "type": "bytes"
      }
    ],
    "name": "createCard",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "exchangeCompleted",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "exchangeRequests",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getAllPendingForUser",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "outgoing",
        "type": "address[]"
      },
      {
        "internalType": "address[]",
        "name": "incoming",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getAllUsers",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "getConnectionCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "getConnections",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "getEncryptedHandles",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "genderHandle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "phoneHandle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "fullNameHandle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "socialIdHandle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "locationHandle",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getMyEncryptedHandles",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "genderHandle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "phoneHandle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "fullNameHandle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "socialIdHandle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "locationHandle",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "getPendingIncoming",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "getPendingOutgoing",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "getPublicInfo",
    "outputs": [
      {
        "internalType": "string",
        "name": "surname",
        "type": "string"
      },
      {
        "internalType": "bool",
        "name": "exists",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getUserCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "hasCard",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "a",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "b",
        "type": "address"
      }
    ],
    "name": "hasCompletedExchange",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "hasRequestedExchange",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "requestExchange",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "surname",
        "type": "string"
      },
      {
        "internalType": "externalEuint8",
        "name": "gender",
        "type": "bytes32"
      },
      {
        "internalType": "externalEuint64",
        "name": "phone",
        "type": "bytes32"
      },
      {
        "internalType": "externalEuint64",
        "name": "fullName",
        "type": "bytes32"
      },
      {
        "internalType": "externalEuint128",
        "name": "socialId",
        "type": "bytes32"
      },
      {
        "internalType": "externalEuint256",
        "name": "location",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "inputProof",
        "type": "bytes"
      }
    ],
    "name": "updateCard",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
